edex_ds_db_image:
  build: ./directoryServer/src/main/docker/db
  expose:
   - "3306"
  container_name: edex-ds-db
edex_ds_app_image:
  build: ./directoryServer/src/main/docker/app_server
  volumes:
     - .:/opt/edexchange
  expose:
   - "8009"
  ports:
   - "8080:8080"
  links:
   - edex_ds_db_image
  container_name: edex-ds-app
edex_ds_proxy_image:
    build: ./directoryServer/src/main/docker/proxy_server
    ports:
      - "80:80"
    links:
      - edex_ds_app_image
    volumes:
     - ./logs:/var/log/apache2
    container_name: edex-ds-proxy